SystemPannel/urls.py
from django.conf import settings 
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video.urls')),
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from . import views
from .views import (
    PlaylistCreateView,
    
)
from video.views import(

	upload_video_view,
	detail_video_view,
	update_video_view,

)

app_name = 'video'

urlpatterns = [
    path('video/', views.home, name='video-home'),
    path('video/createplaylist/', PlaylistCreateView.as_view(), name='playlist-create'),
    path ('upload/',upload_video_view,name="upload"),
	path ('<slug>/',detail_video_view,name="detail"),
	path ('<slug>/update',update_video_view,name="update"),
]

video/models.py
from django.db import models
from django.contrib.auth.models import User
from user.models import UserProfile
from django_slugify_processor.text import slugify
from django.dispatch import receiver
from django.conf import settings
from django.db.models.signals import post_delete, pre_save



# Create your models here.
class Playlist(models.Model):
    creator=models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='created_playlist')
    name=models.CharField(max_length=100)
    viewed_by=models.ManyToManyField(UserProfile, related_name="viewed_playlists")
    size=models.IntegerField()
    Tags=models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Comment(models.Model):
    posted_by=models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    text=models.CharField(max_length=100)
    replies=[]


class Video(models.Model): 

    video=models.CharField(max_length=100)
    subtitle=models.CharField(max_length=100)
    title=models.CharField(max_length=100)
    upvotes=models.IntegerField()
    comments=models.ForeignKey(Comment, on_delete=models.CASCADE)
    views=models.IntegerField()


def upload_location(instance,filename,**kwargs):
	file_path ='video/{author_id}/{title}-{filename}'.format(
			author_id=str(instance.author.id),title=str(instance.title),filename=filename
		)
	return file_path


class VideoUpload(models.Model):
	title						= models.CharField(max_length=50, null=False, blank=False)
	body						= models.TextField(max_length=5000, null=False, blank=False)
	videofile					= models.FileField(upload_to=upload_location, null=True, verbose_name="")
	date_published				= models.DateTimeField(auto_now_add=True,verbose_name="date published")
	date_updated				= models.DateTimeField(auto_now_add=True,verbose_name="date  updated")
	author						= models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	slug						= models.SlugField(blank=True ,unique=True)


	def __str__(self):
		 return self.title 

@receiver(post_delete,sender=VideoUpload)
def submission_delete(sender,instance,**kwargs):
	instance.videofile.delete(False)


def pre_save_upload_video_receiever(sender,instance,*args,**kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-"+instance.title)


pre_save.connect(pre_save_upload_video_receiever,sender=VideoUpload)

video/forms.py
from django import forms 


from video.models import VideoUpload


class UploadVideoForm(forms.ModelForm):

	class Meta:
		model  = VideoUpload
		fields = ['title','body','videofile']



class UpdateVideoForm(forms.ModelForm):


	class Meta:
		model = VideoUpload
		fields = ['title','body','videofile']

	def save(self, commit=True):
		video_post = self.instance
		video_post.title = self.cleaned_data['title']
		video_post.body = self.cleaned_data['body']

		if self.cleaned_data['videofile']:
			video_post.videofile = self.cleaned_data['videofile']

		if commit:
			video_post.save()
		return video_post

video/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from user.models import UserProfile
from django.http import HttpResponse
from .models import Playlist, Video
from django.views.generic import (
    CreateView,
)




 
# Create your views here.
def home(request):
    context = {
        'playlists': Playlist.objects.all()
    }
    return render(request, 'video/home.html', context)

class PlaylistCreateView(CreateView):
    model = Playlist
    fields = ['name', 'Tags']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

def upload_video_view(request):



	context = {}



	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')

	form =  UploadVideoForm(request.POST or None, request.FILES or None )
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email=user.email).first()
		obj.author = author
		obj.save()
		form = UploadVideoForm()


	context['form'] = form


	return render (request,"video/create_video.html",context)


def detail_video_view(request,slug):

	context = {}

	video_post = get_object_or_404(VideoUpload, slug=slug)
	context['video_post'] = video_post

	return render (request, 'video/detail_video.html', context)


def update_video_view(request,slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	video_post = get_object_or_404(VideoUpload,slug=slug)
	if video_post.author != user:
		return HttpResponse("You are not the auther of that post.")

	if request.POST:
		form = UpdateVideoForm(request.POST or None, request.FILES or None, instance=video_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			video_post = obj
	form = UpdateVideoForm(
			initial = {
					"title": video_post.title,
					"body": video_post.body,
					"videofile": video_post.videofile,
			}
		)

	context['form'] = form
	return render (request,'video/update_video.html',context)

video/templates/video/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'video/video.css' %}">

    {% if title %}
        <title>Video Tab - {{ title }}</title>
    {% else %}
        <title>Video Tab</title>
    {% endif %}
</head>
<body>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

video/templates/video/create_video.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">
				
				{% csrf_token %}
				

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Video -->
				<div class="form-group">
					<label for="id_image">Video</label>
					<input  type="file" name="videofile" id="id_video" accept="video/*" required>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">UPLOAD</button>
			</form>	
		</div>
	</div>
</div>




{% endblock content %}

video/templates/video/detail_video.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
	
	.card{
		max_width: 700px;
	}

	.container{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">

		<!--Videopost-->
		<div class="card m-auto">
			
			<video width='400' class="card-img-top" controls>
				<source src="{{video_post.videofile.url}}"  type='video/mp4'>
				Your browser does not support the video tag.
			</video>
			<div class="card-body my-2">
				<h2 class="card-title"> {{video_post.title}}</h2>
				<p class="card-text"> {{video_post.body |safe}}</p>
				{% if video_post.author == request.user %}
					<a href="{% url 'video:update' video_post.slug %}" class ="btn btn-primary">Upload</a>
				{% endif  %}

				
			</div>
			<div class="card-footer text-muted">
				Updated on {{video_post.date_updated}} by {{video_post.author}}
				
			</div>

		<!--end Blog post -->	
		</div>
		
	</div>
	
</div>

{% endblock content %}

video/templates/video/home.html
{% extends 'video/base.html' %}
 
{% block content %}
    <h2>Home </h2>
    {% for playlist in playlists %}
        <h1> {{ playlist.name }} </h1>
        <p> Created by {{ playlist.creator }} </p>
        <p> Views: {{ playlist.viewed_by }}, Size: {{ playlist.size }}, Tags: {{ playlist.Tags }} </p>
    {% endfor %}

{% endblock content %}

video/templates/video/must_authenticate.html
{% extends 'base.html' %}

{% block content %}	

<div class= "container">
	<div class="d-flex flex-column">
		<p class="m-auto">Must authenticate to view this page </p> 
		<p class="m-auto">
				<a href="{% url 'register' %}">Register</a> or
				<a href="{% url 'login' %}">Login </a>
		</p>
	</div>
</div>

{% endblock content %}	

video/templates/video/playlist_form.html
{% extends "video/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Playlist</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create</button>
            </div>
        </form>
    </div>
{% endblock content %}

video/templates/video/update_video.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This video is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Video -->
				<div class="form-group image-group" id="id_video_group">
                    
                    <video width='400' class="img-fluid image"  id="id_video_display"controls>
                        <source src="{{form.initial.videofile.url}}"  type='video/mp4'>
                        Your browser does not support the video tag.
                    </video>
					  <div class="middle">
					    <div class="text">Update</div>
					  </div>
				</div>
				<input type="file" name="videofile" id="id_video_file" accept="video/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_video_group').onclick = function(event){
    	document.getElementById('id_vidoe_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_video_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}